### ISSUE TITLE
Any better way to make rake test run through tapout?

### ISSUE THREAD

**Issue by abinoam** [rubyworks/tapout#10]
The way I could come out is to create a file **lib/tasks/tapout.rake** with

``` ruby
desc "Run 'rake test' through tapout"
task :tapout, [:reporter] do |t, args|
  reporter = args.reporter || "runtime"
  sh "TESTOPTS='- --tapy' bin/rake -q test | tapout #{reporter}" rescue true
end
```

So I can run 

``` ruby
rake tapout
or
rake tapout[outline]
```

It's a little weird to make a Rake task to run rake again! Isn't it?

Is there a better way to do it?
If not, could add this (or any improved one) piece of code as example on the Quick Start guide.
I'm asking this because the directions on the Quick Start guide was not working for me (The pipe '|' was not working when inside TESTOPTS).

Running:

```
minitap (0.5.3)
minitest (5.3.1)
minitest-reporter-api (0.0.5)
rails (4.1.0.rc1)
tapout (0.4.5)
```

**Comment by trans** [comment]
Hmm... why would the pipe not work in TESTOPTS? I'll have to take a look and see what I can work out. I agree, it should not be necessary to call rake from rake.

**Comment by trans** [comment]
Here's basically what I use and it's working for me:

``` ruby
Rake::TestTask.new :test do |t|
  rpt = ENV['rpt'] || 'runtime'

  t.libs << "test"
  t.test_files = FileList['test/test*.rb']
  t.verbose = false
  t.options = " - --tapy | tapout #{rpt}"
end
```

Use like `rpt=pretty rake -q test`.

I'm sure this can be adapted to use a Rake task argument instead of an environment variable, but it's a little tricky b/c Rake's test task doesn't appear to support arguments itself.

**Comment by abinoam** [comment]
I may be doing something wrong, but I didn't manage to make it work the way you did.

**Comment by trans** [comment]
Is it possible for me to see the project your using this on? I want to understand what could prevent this from working right.

**Comment by abinoam** [comment]
I'll try to make a fresh install of rails and try to reproduce the problem.

By now... I have just added RAILS_ENV="test" to the command line.
I have just figured out that it was running in development environment (and messing my development database with the test fixtures).

I have reproduced the behaviour at Mac running Mavericks and at Ubuntu 64 13.10.

Of note... I'm using RVM.

As soon as I have time I will send you the link.

**Comment by trans** [comment]
That would be great. Thanks.

**Comment by abinoam** [comment]
I have just done it!

https://github.com/abinoam/tapout_rails_test_application

Could you try to fork/clone it and see if it's reproducible on your setup?

**Comment by trans** [comment]
Thanks for setting up the example project. That helped me narrow down the issue.

First thing to point out is that `TESTOPTS` only works with Rake. It has no effect when running ruby directly. (In fact, that's what `TESTOPTS` does --it passes those arguments to `ruby` under the hood.)

So in the case of your example,

```
TESTOPTS="--tapy | tapout" ruby  -Itest test/models/friend_test.rb
```

If you just want to do this via Ruby, then `TESTOPTS` isn't needed:

```
ruby  -Itest test/models/friend_test.rb - --tapy | tapout
```

But I assume you want to "rakify" it, I think like so:

```
TESTOPTS="--tapy | tapout" TEST="test/models/friend_test.rb" rake -q test 
```

Unfortunately that's not the end of the problem. While the pipe (`| tapout`) works fine with a regular Ruby project, Rails overrides the Rake's TestTask, and in doing so somehow causes the pipe to be ignored. I don't know how yet. I've inquired about it on Rails github issues. 

In the mean time, a good quick fix might be to add a `bin/test` command to your project where you can add the pipe, e.g.

```
TESTOPTS="--tapy" rake -q test | tapout
```

Then run `bin/test` to test your project. You can modify this as you see fit, of course. For example, I'd probably do:

```
#!/usr/bin/env sh

if [ "$rpt" = "none" ]; then
  rake test
else
  TESTOPTS="--tapy" rake -q test | tapout $rpt
fi
```

**Comment by abinoam** [comment]
Sorry, I was tired when wrote the answer. Thanks for pointing the mistake (showing the line that I was trying to put on Rakefile as a shell line).
But, what I was trying to show is that it doesn't work as you showed in:

``` rake
Rake::TestTask.new :test do |t|
  rpt = ENV['rpt'] || 'runtime'

  t.libs << "test"
  t.test_files = FileList['test/test*.rb']
  t.verbose = false
  t.options = " - --tapy | tapout #{rpt}"
end
```

Good that you were able to reproduce the behaviour.

And, apart from creating the suggested **bin/test** I will keep my rakefile approach meanwhile. 

Thanks a lot for giving attention to the issue.

**Comment by trans** [comment]
Ah okay. I added this to the Rakefile and it worked for me:

``` ruby
Rake::TestTask.new :tapout do |t|
  rpt = ENV['rpt'] || 'runtime'

  t.libs << "test"
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = false
  t.options = " - --tapy | tapout #{rpt}"
end
```

Notice the `test_files` line, I had to change that. Does this work for you? If not, what output do you get? Even if that much work there is still the problem that this is using `Rake::TestTask` instead of `Rails::TestTask` --and the later fails for me too. I'm still looking into this, let you know when I figure more out.

Really appreciate your correspondence on this issue, btw, so I can get it ironed out.

**Comment by trans** [comment]
Okay, I managed to fix my segfault. Had to bypass my system's .deb install of Bundler and then do a `gem pristine --all` to recompile native gems.  (P.S. I deleted my previous "bitch session" post about this, seeing as it was nonconstructive. Sorry.)

So it looks like my above script is working for me. If it's not working for you it would help to know what output you are getting. And I'll let you know when I find out about the `Rails::TestTask` blocking the pipe.

**Comment by abinoam** [comment]
You Rake::TestTask.new is working.
But with the annoying message... 

```
rake aborted!
Command failed with status (255): [ruby -I"lib:test" -I"/Users/abinoam/.rvm/gems/ruby-2.1.0/gems/rake-10.1.1/lib" "/Users/abinoam/.rvm/gems/ruby-2.1.0/gems/rake-10.1.1/lib/rake/rake_test_loader.rb" "test/controllers/friends_controller_test.rb" "test/helpers/friends_helper_test.rb" "test/models/friend_test.rb" "test/models/user_test.rb"  - --tapy | tapout runtime]
```

... for failing tests.

That's why I've put the **rescue** on my approach.

About the RailsTask not working, I would suspect this line.

https://github.com/rails/rails/blob/master/railties/lib/rails/test_unit/sub_test_task.rb#L109

It pass the options to Shellwords.split.

```
 > Shellwords.split " - --tapy | tapout runtime"
 => ["-", "--tapy", "|", "tapout", "runtime"] 
```

**Comment by abinoam** [comment]
Just to keep it clear:

At the command line, this works:

``` sh
TESTOPTS="- --tapy" rake -q test | tapout
```

This doesn't work:

``` sh
TESTOPTS="- --tapy | tapout" rake -q test
```

Perhaps the end of this would be your gem providing the personalized Rake task by default.
I mean, if I put minitap on my Gemfile a task with the name "tapout"  or "minitap" would automatically appear  when I type 'rake -T'. (as for other gem related tasks).

**Comment by trans** [comment]
I concur about that annoying message. But I don't know how to get rid of it and still have Rake exit with a not 0 exit code. It needs to exit with a non-zero exit code for things like Travis CI.

**Comment by trans** [comment]
Unfortunately, https://github.com/jimweirich/rake/issues/265#issuecomment-39516063

**Comment by trans** [comment]
Well, at the very least I did this: https://github.com/rubyworks/tapout/wiki/Quick-Start#tapout-on-rails

A solution that doesn't require rake to shell out to itself would of course be nice, but for the moment it looks like the best solution (as indicated by https://github.com/rails/rails/issues/14553).

**Comment by abinoam** [comment]
Thanks for the credits! :-)
I've just added RAILS_ENV='test' to the suggestion on the wiki.
I'll try to figure out a better way. If I succeed, I'll let you know.

**Comment by trans** [comment]
Awesome, thank you.

FYI I think I am going to split the "Quick Start" guide into separate factoid pages. Should make things a little easier to find and maintain.

**Comment by abinoam** [comment]
I think we forgot to close this! 👍
